; PlatformIO Project Configuration File

[platformio]
description                 = Internetradio with ESP32x, I2S DAC and Display with Touchpad
extra_configs               = platformio_override.ini
;
[common]
monitor_speed = 115200  ; 921600, 512000, 460800, 256000, 115200

build_unflags =
    -D BOARD_SDIO_ESP_HOSTED_CLK
    -D BOARD_SDIO_ESP_HOSTED_CMD
    -D BOARD_SDIO_ESP_HOSTED_D0
    -D BOARD_SDIO_ESP_HOSTED_D1
    -D BOARD_SDIO_ESP_HOSTED_D2
    -D BOARD_SDIO_ESP_HOSTED_D3
    -D BOARD_SDIO_ESP_HOSTED_RESET

build_flags =
    -D CONFIG_ESP_HOSTED_IDF_SLAVE_TARGET='"esp32c6"'
    -D CORE_DEBUG_LEVEL=3                    ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D ARDUINO_RUNNING_CORE=1                ; Arduino Runs On Core (setup, loop)
    -D ARDUINO_EVENT_RUNNING_CORE=1          ; Events Run On Core
    -D BOARD_HAS_PSRAM=1
    -D MONITOR_SPEED=${this.monitor_speed}

    -D BOARD_SDIO_ESP_HOSTED_CLK=18
    -D BOARD_SDIO_ESP_HOSTED_CMD=19
    -D BOARD_SDIO_ESP_HOSTED_D0=14
    -D BOARD_SDIO_ESP_HOSTED_D1=15
    -D BOARD_SDIO_ESP_HOSTED_D2=16
    -D BOARD_SDIO_ESP_HOSTED_D3=17
    -D BOARD_SDIO_ESP_HOSTED_RESET=54    ; 32
    -DCHIP_VARIANT_POSTV3=1

    -Wall
    -Wextra
    -Wno-cpp                                 ; Disable #warning directive warnings
    -Wno-format                              ; Disable all format string warnings
    -Wno-unused-function
    -Wno-missing-field-initializers
    -fdiagnostics-color=always
    -Wno-error=class-memaccess

;—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[env]


; Arduino 3.3.9 IDF 5.5.4
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip

; Arduino 3.3.11 IDF 5.5.5
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip

board_build.filesystem = littlefs

monitor_filters = direct
upload_speed    = 921600  ; 921600, 512000, 460800, 256000, 115200

framework = arduino

custom_component_remove =
                          espressif/network_provisioning
                          espressif/esp-zboss-lib
                          espressif/esp-zigbee-lib
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/qrcode
                          espressif/esp-sr
                          espressif/libsodium
                          espressif/esp-modbus
                          chmorgan/esp-libhelix-mp3
                          espressif/esp32-camera

;—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[env:esp32p4_es]
    board_build.partitions = boards/dev-hosted.csv
    board = ESP32-P4-NRW16-es
    build_flags = ${common.build_flags}
    build_unflags = ${common.build_unflags}
;—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[env:esp32p4]
    board_build.partitions = boards/dev-hosted.csv
    board = ESP32-P4-NRW16
    build_flags = ${common.build_flags}
    build_unflags = ${common.build_unflags}
 ;—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
